# Generated by Django 4.0.2 on 2022-12-29 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_reply_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['title', 'user', '-date']},
        ),
    ]
